// M12 real-site pass: `npm run realsites -- --label "<machine>" [--no-build]`.
// Builds the e2e extension, runs tests/realsites/realSites.spec.ts (one
// observation per site in tests/realsites/sites.ts, mock backend) and writes
// the counts into docs/REAL_SITES.md under the machine label.
//
// Plain Node script (Node 24 strips the types itself), like benchmark.ts.

import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { upsertSection } from './benchmarkTable.ts';
import { renderRealSitesSection, type RealSitesRun } from './realSitesTable.ts';

const ROOT = path.resolve(fileURLToPath(import.meta.url), '../..');
const DOC = path.join(ROOT, 'docs/REAL_SITES.md');
const DOC_HEADER = `# Edward — Real-site pass

Generated by \`npm run realsites -- --label "<machine>"\` (M12, SPEC §18.1 on real pages). Each
site in \`tests/realsites/sites.ts\` is loaded logged out on a fresh profile, and the e2e build's
hook runs one observation with the **mock backend**: nothing goes to a reasoning backend. Only
counts and timings are recorded. Page text never leaves the test process.

Reading the tables:
- **outcome**: \`ok\`; \`blocked\` (the §14 final guard withheld the observation); \`timeout\` (no
  observation within 120 s); \`error\`; \`nav_failed\` (the page didn't load).
- **observe ms**: wall time of the whole observation in the content script (Phase A, Phase B,
  images the assembler waits for, assembly).
- **\`sanitize.chunk\`**: one whole sanitization message (regex plus the awaited NER). Sections from
  before M12 call it \`sanitize.regex\`; it's the same measurement.
- **tokens**: distinct \`[PII_<TYPE>_n]\` tokens in the outgoing observation.
- **leak candidates**: regex-tier hits left in the outgoing text (\`src/sanitize/residualScan.ts\`).
  The pipeline tokenizes every regex hit except emails the §7.5 heuristic keeps public, so any
  count here is investigated. Emails with a public signal (role address or same-site domain) are
  counted separately as \`EMAIL_LIKELY_PUBLIC\` in the second table.
- **truncated**: the §14.2 budget (M12, \`src/dom/contentBudget.ts\`) left content out; the count
  is nodes flagged \`trimmed\`. **text KB** is the observation JSON without images (what counts
  against a backend's context); **image KB** is the images as base64.
- Per-op columns are p50 / p95 ms from the metrics log over that site's visit.
`;

const { values } = parseArgs({ options: { label: { type: 'string' }, 'no-build': { type: 'boolean' } } });
if (!values.label) {
  console.error('usage: npm run realsites -- --label "<machine>" [--no-build]');
  process.exit(2);
}
const label = values.label;

function run(cmd: string, args: string[], env: Record<string, string>): boolean {
  return spawnSync(cmd, args, { cwd: ROOT, stdio: 'inherit', env: { ...process.env, ...env } }).status === 0;
}

const out = path.join(ROOT, '.output/realsites.json');
const env = { EDWARD_E2E: '1', EDWARD_REALSITES_OUT: out };
if (!values['no-build'] && !run('npx', ['wxt', 'build'], env)) {
  console.error('build failed');
  process.exit(1);
}
if (!run('npx', ['playwright', 'test', '-c', 'playwright.realsites.config.ts'], env) || !existsSync(out)) {
  console.error('real-site run failed; docs/REAL_SITES.md unchanged');
  process.exit(1);
}

const result = JSON.parse(await readFile(out, 'utf8')) as RealSitesRun;
const section = renderRealSitesSection(label, new Date().toISOString().slice(0, 10), result);
const doc = existsSync(DOC) ? await readFile(DOC, 'utf8') : DOC_HEADER;
await writeFile(DOC, upsertSection(doc, label, section));
console.log(`\n${section}\nwritten to docs/REAL_SITES.md`);
